{
    "data": {
        "A": [{
            "countryId": "AF",
            "countryName": "Afghanistan",
            "letter": "A"
        }, {
            "countryId": "AL",
            "countryName": "Albania",
            "letter": "A"
        }, {
            "countryId": "DZ",
            "countryName": "Algeria",
            "letter": "A"
        }, {
            "countryId": "AS",
            "countryName": "American Samoa",
            "letter": "A"
        }, {
            "countryId": "AD",
            "countryName": "Andorra",
            "letter": "A"
        }, {
            "countryId": "AO",
            "countryName": "Angola",
            "letter": "A"
        }, {
            "countryId": "AI",
            "countryName": "Anguilla",
            "letter": "A"
        }, {
            "countryId": "AG",
            "countryName": "Antigua and Barbuda",
            "letter": "A"
        }, {
            "countryId": "AR",
            "countryName": "Argentina",
            "letter": "A"
        }, {
            "countryId": "AM",
            "countryName": "Armenia",
            "letter": "A"
        }, {
            "countryId": "AW",
            "countryName": "Aruba",
            "letter": "A"
        }, {
            "countryId": "AU",
            "countryName": "Australia",
            "letter": "A"
        }, {
            "countryId": "AT",
            "countryName": "Austria",
            "letter": "A"
        }, {
            "countryId": "AZ",
            "countryName": "Azerbaijan",
            "letter": "A"
        }],
        "B": [{
            "countryId": "BS",
            "countryName": "Bahamas",
            "letter": "B"
        }, {
            "countryId": "BH",
            "countryName": "Bahrain",
            "letter": "B"
        }, {
            "countryId": "BD",
            "countryName": "Bangladesh",
            "letter": "B"
        }, {
            "countryId": "BB",
            "countryName": "Barbados",
            "letter": "B"
        }, {
            "countryId": "BY",
            "countryName": "Belarus",
            "letter": "B"
        }, {
            "countryId": "BE",
            "countryName": "Belgium",
            "letter": "B"
        }, {
            "countryId": "BZ",
            "countryName": "Belize",
            "letter": "B"
        }, {
            "countryId": "BJ",
            "countryName": "Benin",
            "letter": "B"
        }, {
            "countryId": "BM",
            "countryName": "Bermuda",
            "letter": "B"
        }, {
            "countryId": "BT",
            "countryName": "Bhutan",
            "letter": "B"
        }, {
            "countryId": "BO",
            "countryName": "Bolivia",
            "letter": "B"
        }, {
            "countryId": "BA",
            "countryName": "Bosnia and Hercegovina",
            "letter": "B"
        }, {
            "countryId": "BW",
            "countryName": "Botswana",
            "letter": "B"
        }, {
            "countryId": "BR",
            "countryName": "Brazil",
            "letter": "B"
        }, {
            "countryId": "VG",
            "countryName": "British Virgin Islands",
            "letter": "B"
        }, {
            "countryId": "BN",
            "countryName": "Brunei",
            "letter": "B"
        }, {
            "countryId": "BG",
            "countryName": "Bulgaria",
            "letter": "B"
        }, {
            "countryId": "BF",
            "countryName": "Burkina Faso",
            "letter": "B"
        }, {
            "countryId": "BI",
            "countryName": "Burundi",
            "letter": "B"
        }],
        "C": [{
            "countryId": "CN",
            "countryName": "China",
            "letter": "C"
        }, {
            "countryId": "KH",
            "countryName": "Cambodia",
            "letter": "C"
        }, {
            "countryId": "CM",
            "countryName": "Cameroon",
            "letter": "C"
        }, {
            "countryId": "CA",
            "countryName": "Canada",
            "letter": "C"
        }, {
            "countryId": "CS",
            "countryName": "CanaryIslands",
            "letter": "C"
        }, {
            "countryId": "CV",
            "countryName": "Cape Verde",
            "letter": "C"
        }, {
            "countryId": "KY",
            "countryName": "Cayman Islands",
            "letter": "C"
        }, {
            "countryId": "CF",
            "countryName": "Central African Republic",
            "letter": "C"
        }, {
            "countryId": "TD",
            "countryName": "Chad",
            "letter": "C"
        }, {
            "countryId": "CL",
            "countryName": "Chile",
            "letter": "C"
        }, {
            "countryId": "CN",
            "countryName": "China",
            "letter": "C"
        }, {
            "countryId": "CO",
            "countryName": "Colombia",
            "letter": "C"
        }, {
            "countryId": "KM",
            "countryName": "Comoros",
            "letter": "C"
        }, {
            "countryId": "CK",
            "countryName": "Cook Islands",
            "letter": "C"
        }, {
            "countryId": "CR",
            "countryName": "Costa Rica",
            "letter": "C"
        }, {
            "countryId": "HR",
            "countryName": "Croatia",
            "letter": "C"
        }, {
            "countryId": "CU",
            "countryName": "Cuba",
            "letter": "C"
        }, {
            "countryId": "CY",
            "countryName": "Cyprus",
            "letter": "C"
        }, {
            "countryId": "CZ",
            "countryName": "Czech Republic",
            "letter": "C"
        }],
        "D": [{
            "countryId": "CD",
            "countryName": "Democratic Republic of Congo",
            "letter": "D"
        }, {
            "countryId": "DK",
            "countryName": "Denmark",
            "letter": "D"
        }, {
            "countryId": "DJ",
            "countryName": "Djibouti",
            "letter": "D"
        }, {
            "countryId": "DM",
            "countryName": "Dominica",
            "letter": "D"
        }, {
            "countryId": "DO",
            "countryName": "Dominican Republic",
            "letter": "D"
        }],
        "E": [{
            "countryId": "TL",
            "countryName": "East Timor",
            "letter": "E"
        }, {
            "countryId": "EC",
            "countryName": "Ecuador",
            "letter": "E"
        }, {
            "countryId": "EG",
            "countryName": "Egypt",
            "letter": "E"
        }, {
            "countryId": "SV",
            "countryName": "El Salvador",
            "letter": "E"
        }, {
            "countryId": "GQ",
            "countryName": "Equatorial Guinea",
            "letter": "E"
        }, {
            "countryId": "ER",
            "countryName": "Eritrea",
            "letter": "E"
        }, {
            "countryId": "EE",
            "countryName": "Estonia",
            "letter": "E"
        }, {
            "countryId": "ET",
            "countryName": "Ethiopia",
            "letter": "E"
        }],
        "F": [{
            "countryId": "FO",
            "countryName": "Faeroe Islands",
            "letter": "F"
        }, {
            "countryId": "FK",
            "countryName": "Falkland Islands",
            "letter": "F"
        }, {
            "countryId": "FJ",
            "countryName": "Fiji",
            "letter": "F"
        }, {
            "countryId": "FI",
            "countryName": "Finland",
            "letter": "F"
        }, {
            "countryId": "FR",
            "countryName": "France",
            "letter": "F"
        }, {
            "countryId": "GF",
            "countryName": "French Guiana",
            "letter": "F"
        }, {
            "countryId": "PF",
            "countryName": "French Polynesia",
            "letter": "F"
        }],
        "G": [{
            "countryId": "GA",
            "countryName": "Gabon",
            "letter": "G"
        }, {
            "countryId": "GM",
            "countryName": "Gambia",
            "letter": "G"
        }, {
            "countryId": "GE",
            "countryName": "Georgia",
            "letter": "G"
        }, {
            "countryId": "DE",
            "countryName": "Germany",
            "letter": "G"
        }, {
            "countryId": "GH",
            "countryName": "Ghana",
            "letter": "G"
        }, {
            "countryId": "GI",
            "countryName": "Gibraltar",
            "letter": "G"
        }, {
            "countryId": "GR",
            "countryName": "Greece",
            "letter": "G"
        }, {
            "countryId": "GL",
            "countryName": "Greenland",
            "letter": "G"
        }, {
            "countryId": "GD",
            "countryName": "Grenada",
            "letter": "G"
        }, {
            "countryId": "GP",
            "countryName": "Guadeloupe",
            "letter": "G"
        }, {
            "countryId": "GU",
            "countryName": "Guam",
            "letter": "G"
        }, {
            "countryId": "GT",
            "countryName": "Guatemala",
            "letter": "G"
        }, {
            "countryId": "GN",
            "countryName": "Guinea",
            "letter": "G"
        }, {
            "countryId": "GW",
            "countryName": "Guinea-Bissau",
            "letter": "G"
        }, {
            "countryId": "GY",
            "countryName": "Guyana",
            "letter": "G"
        }],
        "H": [{
            "countryId": "HT",
            "countryName": "Haiti",
            "letter": "H"
        }, {
            "countryId": "HN",
            "countryName": "Honduras",
            "letter": "H"
        }, {
            "countryId": "HK",
            "countryName": "Hong Kong",
            "letter": "H"
        }, {
            "countryId": "HU",
            "countryName": "Hungary",
            "letter": "H"
        }],
        "I": [{
            "countryId": "IS",
            "countryName": "Iceland",
            "letter": "I"
        }, {
            "countryId": "IN",
            "countryName": "India",
            "letter": "I"
        }, {
            "countryId": "ID",
            "countryName": "Indonesia",
            "letter": "I"
        }, {
            "countryId": "IR",
            "countryName": "Iran",
            "letter": "I"
        }, {
            "countryId": "IQ",
            "countryName": "Iraq",
            "letter": "I"
        }, {
            "countryId": "IE",
            "countryName": "Ireland",
            "letter": "I"
        }, {
            "countryId": "IL",
            "countryName": "Israel",
            "letter": "I"
        }, {
            "countryId": "IT",
            "countryName": "Italy",
            "letter": "I"
        }, {
            "countryId": "CI",
            "countryName": "Ivory Coast",
            "letter": "I"
        }],
        "J": [{
            "countryId": "JM",
            "countryName": "Jamaica",
            "letter": "J"
        }, {
            "countryId": "JP",
            "countryName": "Japan",
            "letter": "J"
        }, {
            "countryId": "JO",
            "countryName": "Jordan",
            "letter": "J"
        }],
        "K": [{
            "countryId": "KZ",
            "countryName": "Kazakhstan",
            "letter": "K"
        }, {
            "countryId": "KE",
            "countryName": "Kenya",
            "letter": "K"
        }, {
            "countryId": "KG",
            "countryName": "Kirghizia (formerly Kyrgyzstan)",
            "letter": "K"
        }, {
            "countryId": "KI",
            "countryName": "Kiribati",
            "letter": "K"
        }, {
            "countryId": "KW",
            "countryName": "Kuwait",
            "letter": "K"
        }],
        "L": [{
            "countryId": "LA",
            "countryName": "Laos",
            "letter": "L"
        }, {
            "countryId": "LV",
            "countryName": "Latvia",
            "letter": "L"
        }, {
            "countryId": "LB",
            "countryName": "Lebanon",
            "letter": "L"
        }, {
            "countryId": "LS",
            "countryName": "Lesotho",
            "letter": "L"
        }, {
            "countryId": "LR",
            "countryName": "Liberia",
            "letter": "L"
        }, {
            "countryId": "LY",
            "countryName": "Libya",
            "letter": "L"
        }, {
            "countryId": "LI",
            "countryName": "Liechtenstein",
            "letter": "L"
        }, {
            "countryId": "LT",
            "countryName": "Lithuania",
            "letter": "L"
        }, {
            "countryId": "LU",
            "countryName": "Luxembourg",
            "letter": "L"
        }],
        "M": [{
            "countryId": "MO",
            "countryName": "Macau",
            "letter": "M"
        }, {
            "countryId": "MK",
            "countryName": "Macedonia",
            "letter": "M"
        }, {
            "countryId": "MG",
            "countryName": "Madagascar",
            "letter": "M"
        }, {
            "countryId": "MW",
            "countryName": "Malawi",
            "letter": "M"
        }, {
            "countryId": "MY",
            "countryName": "Malaysia",
            "letter": "M"
        }, {
            "countryId": "MV",
            "countryName": "Maldives",
            "letter": "M"
        }, {
            "countryId": "ML",
            "countryName": "Mali",
            "letter": "M"
        }, {
            "countryId": "MT",
            "countryName": "Malta",
            "letter": "M"
        }, {
            "countryId": "MH",
            "countryName": "Marshall Islands",
            "letter": "M"
        }, {
            "countryId": "MQ",
            "countryName": "Martinique",
            "letter": "M"
        }, {
            "countryId": "MR",
            "countryName": "Mauritania",
            "letter": "M"
        }, {
            "countryId": "MU",
            "countryName": "Mauritius",
            "letter": "M"
        }, {
            "countryId": "MX",
            "countryName": "Mexico",
            "letter": "M"
        }, {
            "countryId": "FM",
            "countryName": "Micronesia,Federated States of",
            "letter": "M"
        }, {
            "countryId": "MD",
            "countryName": "Moldova",
            "letter": "M"
        }, {
            "countryId": "MC",
            "countryName": "Monaco",
            "letter": "M"
        }, {
            "countryId": "MN",
            "countryName": "Mongolia",
            "letter": "M"
        }, {
            "countryId": "ME",
            "countryName": "Montenegro",
            "letter": "M"
        }, {
            "countryId": "MS",
            "countryName": "Montserrat",
            "letter": "M"
        }, {
            "countryId": "MA",
            "countryName": "Morocco",
            "letter": "M"
        }, {
            "countryId": "MZ",
            "countryName": "Mozambique",
            "letter": "M"
        }, {
            "countryId": "MM",
            "countryName": "Myanmar",
            "letter": "M"
        }],
        "N": [{
            "countryId": "NA",
            "countryName": "Namibia",
            "letter": "N"
        }, {
            "countryId": "NR",
            "countryName": "Nauru",
            "letter": "N"
        }, {
            "countryId": "NP",
            "countryName": "Nepal",
            "letter": "N"
        }, {
            "countryId": "AN",
            "countryName": "Netherlands Antilles",
            "letter": "N"
        }, {
            "countryId": "NL",
            "countryName": "Netherlands(Holland)",
            "letter": "N"
        }, {
            "countryId": "NC",
            "countryName": "New Caledonia",
            "letter": "N"
        }, {
            "countryId": "NZ",
            "countryName": "New Zealand",
            "letter": "N"
        }, {
            "countryId": "NI",
            "countryName": "Nicaragua",
            "letter": "N"
        }, {
            "countryId": "NE",
            "countryName": "Niger",
            "letter": "N"
        }, {
            "countryId": "NG",
            "countryName": "Nigeria",
            "letter": "N"
        }, {
            "countryId": "NU",
            "countryName": "Niue",
            "letter": "N"
        }, {
            "countryId": "NF",
            "countryName": "Norfolk Island",
            "letter": "N"
        }, {
            "countryId": "MP",
            "countryName": "Northern Mariana islands",
            "letter": "N"
        }, {
            "countryId": "NO",
            "countryName": "Norway",
            "letter": "N"
        }],
        "O": [{
            "countryId": "OM",
            "countryName": "Oman",
            "letter": "O"
        }],
        "P": [{
            "countryId": "PK",
            "countryName": "Pakistan",
            "letter": "P"
        }, {
            "countryId": "PW",
            "countryName": "Palau",
            "letter": "P"
        }, {
            "countryId": "PA",
            "countryName": "Panama",
            "letter": "P"
        }, {
            "countryId": "PG",
            "countryName": "Papua New Guinea",
            "letter": "P"
        }, {
            "countryId": "PY",
            "countryName": "Paraguay",
            "letter": "P"
        }, {
            "countryId": "PE",
            "countryName": "Peru",
            "letter": "P"
        }, {
            "countryId": "PH",
            "countryName": "Philippines",
            "letter": "P"
        }, {
            "countryId": "PL",
            "countryName": "Poland",
            "letter": "P"
        }, {
            "countryId": "PT",
            "countryName": "Portugal",
            "letter": "P"
        }, {
            "countryId": "PR",
            "countryName": "Puerto Rico",
            "letter": "P"
        }],
        "Q": [{
            "countryId": "QA",
            "countryName": "Qatar",
            "letter": "Q"
        }],
        "R": [{
            "countryId": "RE",
            "countryName": "Reunion Island",
            "letter": "R"
        }, {
            "countryId": "RO",
            "countryName": "Romania",
            "letter": "R"
        }, {
            "countryId": "RU",
            "countryName": "Russia",
            "letter": "R"
        }, {
            "countryId": "RW",
            "countryName": "Rwanda",
            "letter": "R"
        }],
        "S": [{
            "countryId": "KN",
            "countryName": "Saint Kitts and Nevis",
            "letter": "S"
        }, {
            "countryId": "LC",
            "countryName": "Saint Lucia",
            "letter": "S"
        }, {
            "countryId": "VC",
            "countryName": "Saint Vincent and Grenadines",
            "letter": "S"
        }, {
            "countryId": "WS",
            "countryName": "Samoa",
            "letter": "S"
        }, {
            "countryId": "SM",
            "countryName": "San Marino",
            "letter": "S"
        }, {
            "countryId": "ST",
            "countryName": "Sao Tome and Principe",
            "letter": "S"
        }, {
            "countryId": "SA",
            "countryName": "Saudi Arabia",
            "letter": "S"
        }, {
            "countryId": "SN",
            "countryName": "Senegal",
            "letter": "S"
        }, {
            "countryId": "RS",
            "countryName": "Serbia",
            "letter": "S"
        }, {
            "countryId": "SC",
            "countryName": "Seychelles",
            "letter": "S"
        }, {
            "countryId": "SL",
            "countryName": "Sierra Leone",
            "letter": "S"
        }, {
            "countryId": "SG",
            "countryName": "Singapore",
            "letter": "S"
        }, {
            "countryId": "SK",
            "countryName": "Slovakia",
            "letter": "S"
        }, {
            "countryId": "SI",
            "countryName": "Slovenia",
            "letter": "S"
        }, {
            "countryId": "SB",
            "countryName": "Solomon Islands",
            "letter": "S"
        }, {
            "countryId": "SO",
            "countryName": "Somalia",
            "letter": "S"
        }, {
            "countryId": "ZA",
            "countryName": "South Africa",
            "letter": "S"
        }, {
            "countryId": "KR",
            "countryName": "South Korea",
            "letter": "S"
        }, {
            "countryId": "ES",
            "countryName": "Spain",
            "letter": "S"
        }, {
            "countryId": "LK",
            "countryName": "Sri Lanka",
            "letter": "S"
        }, {
            "countryId": "SD",
            "countryName": "Sudan",
            "letter": "S"
        }, {
            "countryId": "SR",
            "countryName": "Suriname",
            "letter": "S"
        }, {
            "countryId": "SZ",
            "countryName": "Swaziland",
            "letter": "S"
        }, {
            "countryId": "SE",
            "countryName": "Sweden",
            "letter": "S"
        }, {
            "countryId": "CH",
            "countryName": "Switzerland",
            "letter": "S"
        }, {
            "countryId": "SY",
            "countryName": "Syria",
            "letter": "S"
        }],
        "T": [{
            "countryId": "TW",
            "countryName": "Taiwan",
            "letter": "T"
        }, {
            "countryId": "TJ",
            "countryName": "Tajikistan",
            "letter": "T"
        }, {
            "countryId": "TZ",
            "countryName": "Tanzania",
            "letter": "T"
        }, {
            "countryId": "TH",
            "countryName": "Thailand",
            "letter": "T"
        }, {
            "countryId": "CG",
            "countryName": "The Republic of Congo",
            "letter": "T"
        }, {
            "countryId": "TG",
            "countryName": "Togo",
            "letter": "T"
        }, {
            "countryId": "TO",
            "countryName": "Tonga",
            "letter": "T"
        }, {
            "countryId": "TT",
            "countryName": "Trinidad and Tobago",
            "letter": "T"
        }, {
            "countryId": "TN",
            "countryName": "Tunisia",
            "letter": "T"
        }, {
            "countryId": "TR",
            "countryName": "Turkey",
            "letter": "T"
        }, {
            "countryId": "TM",
            "countryName": "Turkmenistan",
            "letter": "T"
        }, {
            "countryId": "TC",
            "countryName": "Turks and Caicos Islands",
            "letter": "T"
        }, {
            "countryId": "TV",
            "countryName": "Tuvalu",
            "letter": "T"
        }],
        "U": [{
            "countryId": "VI",
            "countryName": "US Virgin Islands",
            "letter": "U"
        }, {
            "countryId": "UG",
            "countryName": "Uganda",
            "letter": "U"
        }, {
            "countryId": "UA",
            "countryName": "Ukraine",
            "letter": "U"
        }, {
            "countryId": "AE",
            "countryName": "United Arab Emirates",
            "letter": "U"
        }, {
            "countryId": "UK",
            "countryName": "United Kingdom",
            "letter": "U"
        }, {
            "countryId": "US",
            "countryName": "United States",
            "letter": "U"
        }, {
            "countryId": "UY",
            "countryName": "Uruguay",
            "letter": "U"
        }, {
            "countryId": "UZ",
            "countryName": "Uzbekistan",
            "letter": "U"
        }],
        "V": [{
            "countryId": "VU",
            "countryName": "Vanuatu",
            "letter": "V"
        }, {
            "countryId": "VA",
            "countryName": "Vatican City",
            "letter": "V"
        }, {
            "countryId": "VE",
            "countryName": "Venezuela",
            "letter": "V"
        }, {
            "countryId": "VN",
            "countryName": "VietNam",
            "letter": "V"
        }],
        "W": [{
            "countryId": "WF",
            "countryName": "Wallis and Futuna Islands",
            "letter": "W"
        }],
        "Y": [{
            "countryId": "YE",
            "countryName": "Yemen,Repubic of",
            "letter": "Y"
        }],
        "Z": [{
            "countryId": "ZM",
            "countryName": "Zambia",
            "letter": "Z"
        }, {
            "countryId": "ZW",
            "countryName": "Zimbabwe",
            "letter": "Z"
        }]
    },
    "message": "Success",
    "serverTime": 1442474442160,
    "state": "0x0000"
}
