{
    "data": {
        "itemWinDtos": [
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005236_00/1.thumb.jpg",
                "itemName": "a111 Ethnic Clothing)",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 1,
                    "promoclass": ""
                },
                "itemcode": "154002762",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "a111-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005238_00/1.thumb.jpg",
                "itemName": "1w a111 Ethnic Clothing)",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002763",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "1w-a111-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005240_00/1.thumb.jpg",
                "itemName": "w2 1w a111 Ethnic Clothing)",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002764",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "w2-1w-a111-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005243_00/1.thumb.jpg",
                "itemName": "r3 Ethnic Clothing)",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002765",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "r3-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005245_00/1.thumb.jpg",
                "itemName": "r22 r3 Ethnic Clothing)",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002766",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "r22-r3-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005247_00/1.thumb.jpg",
                "itemName": "ff r22 r3 Ethnic Clothing)",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002767",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "ff-r22-r3-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005249_00/1.thumb.jpg",
                "itemName": "fs2 r3 Ethnic Clothing)",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002768",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "fs2-r3-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005251_00/1.thumb.jpg",
                "itemName": "dds3 Ethnic Clothing)",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002769",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "dds3-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005253_00/1.thumb.jpg",
                "itemName": "xcx s3 Ethnic Clothing)",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002770",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "xcx-s3-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005255_00/1.thumb.jpg",
                "itemName": "vff4 s3 Ethnic Clothing)",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002771",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "vff4-s3-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005257_00/1.thumb.jpg",
                "itemName": "ccc Ethnic Clothing)-lot",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002772",
                "maxprice": 0,
                "measureName": "Inch",
                "minOrder": 2,
                "minPrice": 123.04,
                "seoItemName": "ccc-ethnic-clothing-",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005771_00/1.thumb.jpg",
                "itemName": "e1 Evening Bags",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002822",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "e1-evening-bags",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005773_00/1.thumb.jpg",
                "itemName": "e2 e1 Evening Bagse2 e1 Evening Bagse2 e1 Evening Bagse2 e1 Evening Bagse2 e1 Evening Bagse2 e1 Evening Bagse2 e1 Evening Bagse2 e1 Evening",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002823",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1047119.38,
                "seoItemName": "e2-e1-evening-bags",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005805_00/1.thumb.jpg",
                "itemName": "e1 Casual Shoese1 Casual Shoese1 Casual Shoese1 Casual Shoese1 Casual Shoese1 Casual Shoese1 Casual Shoese1 Casual Shoese1 Casual Shoese1 Ca",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002832",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 2,
                "minPrice": 523559.69,
                "seoItemName": "e1-casual-shoes",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005826_00/1.thumb.jpg",
                "itemName": "e2 rv e1 Casual Shoes",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002839",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 2,
                "minPrice": 523559.69,
                "seoItemName": "e2-rv-e1-casual-shoes",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005850_00/1.thumb.jpg",
                "itemName": "Camcorders",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002845",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 10470.16,
                "seoItemName": "camcorders",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005852_00/1.thumb.jpg",
                "itemName": "e1 Camcorders",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002846",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 10470.16,
                "seoItemName": "e1-camcorders",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005854_00/1.thumb.jpg",
                "itemName": "e3 e1 Camcorders",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002847",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 10470.16,
                "seoItemName": "e3-e1-camcorders",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005856_00/1.thumb.jpg",
                "itemName": "e2 e3 e1 Camcorders",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002848",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 10470.16,
                "seoItemName": "e2-e3-e1-camcorders",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005858_00/1.thumb.jpg",
                "itemName": "e4 e2 e3 e1 Camcorders",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002849",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 10470.16,
                "seoItemName": "e4-e2-e3-e1-camcorders",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUGm92IRx-tAAMWQALjN1sAAAAFQJTlNMAAxZY751.jpg",
                "itemName": "QA--test--20150316--2",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616009",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 4,
                "minPrice": 230.37,
                "seoItemName": "qa-test-20150316-2",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUGnF2IJ1FxAABYvPYXQ4MAAAAFQJWqysAAFjU981.jpg",
                "itemName": "QA--HH--test--20150316",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616010",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 13.09,
                "seoItemName": "qa-hh-test-20150316",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUGnKqIXaZYAABlHGPln1sAAAAFQJXA_8AAGU0344.jpg",
                "itemName": "QA--HH--test--20150316--1",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616011",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 14.14,
                "seoItemName": "qa-hh-test-20150316-1",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUDAWOIMNapAAKihnlKUAYAAAAFQJNmHcAAqKe016.jpg",
                "itemName": "test-hh-2",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616006",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 544.51,
                "seoItemName": "test-hh-2",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUC4eSIYIrEAAI2i-5QaggAAAAFQJGkrsAAjaj963.jpg",
                "itemName": "Casual Shoes-2",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616001",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1294.25,
                "seoItemName": "casual-shoes-2",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUC4Z2IWC9mAADkKrW7J-AAAAAFQJFrnkAAORC975.jpg",
                "itemName": "Casual Shoes-1",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616000",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 1294.25,
                "seoItemName": "casual-shoes-1",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUGx0CIMJwYAAH-Cklrk0MAAAAFQKL_NYAAf4i126.jpg",
                "itemName": "Other Bathroom Sets mascot",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616030",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 128.8,
                "seoItemName": "other-bathroom-sets",
                "soldNum": 0
            },
            {
                "isfreeShipping": true,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVVdkCuIGDYcAABvVaEH2cEAAAAFwLRGBgAAG9t764.jpg",
                "itemName": "duo beihuo",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616590",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 116.24,
                "seoItemName": "duo-beihuo",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUGnOuIb3BVAAAki-rmXlkAAAAFQJXaTMAACSj447.jpg",
                "itemName": "QA--HH--test--20150316--2",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616012",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 14.14,
                "seoItemName": "qa-hh-test-20150316-2",
                "soldNum": 0
            },
            {
                "isfreeShipping": true,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUGnVaIEsP8AAKteinbfk4AAAAFQJXjdYAAq2S559.jpg",
                "itemName": "test--20150316",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616013",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 26.18,
                "seoItemName": "test-20150316",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUGvxOILo7eAAj-cqPezhQAAAAFQJ6mC4ACP6K677.jpg",
                "itemName": "Computers & Networking&gt;Scanners",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616024",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 130.9,
                "seoItemName": "computers-networking-gt-scanners",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUGvpOIZAUyAAE3eHAtJ3QAAAAFQJ5YJ4AATeQ629.jpg",
                "itemName": "Computers & Networking&gt;Laptops",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616023",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 261.79,
                "seoItemName": "computers-networking-gt-laptops",
                "soldNum": 0
            },
            {
                "isfreeShipping": true,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVV1X0OII8P3AAA4vHe0XHsAAAAGALxTcAAADjU932.jpg",
                "itemName": "Apparel sku-word-2-option",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616757",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 3595.82,
                "seoItemName": "apparel-sku-word-2-option",
                "soldNum": 0
            },
            {
                "isfreeShipping": true,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVS3iZaIYk78AABDPIKwlA0AAAAFQDpQX0AAENU897.jpg",
                "itemName": "Wedding & Events different price 001",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154005515",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 2.1,
                "seoItemName": "wedding-events-different-price-001",
                "soldNum": 0
            },
            {
                "isfreeShipping": true,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVS3jriINPYfAAAY0DzWlTMAAAAFQDrGqUAABjo296.jpg",
                "itemName": "Wedding & Events different price 009 lot",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154005520",
                "maxprice": 0,
                "measureName": "Set",
                "minOrder": 2,
                "minPrice": 7.19,
                "seoItemName": "wedding-events-different-price-009-lot",
                "soldNum": 0
            },
            {
                "isfreeShipping": true,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVS3jZ2IIeKrAABWVp6PCisAAAAFQDqxDcAAFZu721.jpg",
                "itemName": "Wedding & Events different price 009",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154005519",
                "maxprice": 0,
                "measureName": "Ounce",
                "minOrder": 2,
                "minPrice": 0.53,
                "seoItemName": "wedding-events-different-price-009",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005860_00/1.thumb.jpg",
                "itemName": "q1 Camcorders",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002850",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 10470.16,
                "seoItemName": "q1-camcorders",
                "soldNum": 0
            },
            {
                "isfreeShipping": true,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180006130_00/1.thumb.jpg",
                "itemName": "Empire Wedding Dresses",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002888",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 247.13,
                "seoItemName": "empire-wedding-dresses",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/albu_180005862_00/1.thumb.jpg",
                "itemName": "1q q1 Camcorders",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "154002851",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 10470.16,
                "seoItemName": "1q-q1-camcorders",
                "soldNum": 0
            },
            {
                "isfreeShipping": false,
                "ispromo": false,
                "itemImgUrl": "http://www.dhresource.com/100x100/f2/albu/g1/M00/00/00/wKjfHVUDAN2IEY5GAADKzI6d-kYAAAAFQJLYhIAAMrk209.jpg",
                "itemName": "Bubble Bat",
                "itemWinPromoDto": {
                    "discountRate": 0,
                    "dynamicType": 0,
                    "promoMaxPrice": 0,
                    "promoMinPrice": 0,
                    "promoTypeId": 0,
                    "promoclass": ""
                },
                "itemcode": "218616035",
                "maxprice": 0,
                "measureName": "Piece",
                "minOrder": 1,
                "minPrice": 56.44,
                "seoItemName": "bubble-bat",
                "soldNum": 0
            }
        ],
        "totalRecord": 81
    },
    "message": "Success",
    "serverTime": 1445853209848,
    "state": "0x0000"
}