/**
 * Created by zhaojing1 on 2015/1/20.
 */
var msgObj={
	hello:"Hola",
	sign_out:"Cerrar sesión",
	close:"cerca",
	cancel:"Cancelar",
	apply:"Aplicar",
	reset:"Reiniciar",
	max:"Máximo",
	min:"Mínimo",
	filter:"Filtro",
	cas:"Categorías",
	price:"Precio",
	less_than:"Menos de",
	clear_history:"Borrar historial",
	input_key_word:"Por favor ingrese una palabra clave.",
	hot_search:"Más buscados",
	free_shipping:"Envío gratuito",
	wholesale:"Al por mayor",
	reviews:"Comentarios",
	l_best_match:"Mejor coincidencia",
	l_price_lth:"Precio: bajo a alto",
	l_price_htl:"Precio: alto a bajo.",
	l_items_htl:"Artículos vendidos: Alto a bajo.",
	l_recent_list:"Listados recientemente.",
	l_feedback:"Comentario",
	l_all_cas:"Todas las categorías",
	l_min_order:"Orden mínima.",
	PO_PAY_enter_State:"Por favor ingrese un estado, provincia o región válida.",
	PO_only_number:"Solamente se permiten numeros.",
	PO_PAY_emptyError_contactName:"Por favor introduce tu nombre. Si tienes segundo nombre, por favor incluirlo junto con tu nombre.",
	PO_PAY_emptyError_lastName:"El apellido es requerido o la entrega no podria ser completada.",
	PO_PAY_emptyError_addressline1:"Por favor introduce una dirección válida.",
	PO_PAY_emptyError_city:"Por favor introduce una ciudad de facturación válida.",
	PO_PAY_emptyError_postalcode:"Por favor introduce un código postal válido.",
	PO_PAY_emptyError_tel:"Por favor introduce un numero de telefono válido.",
	PO_PAY_emptyError_country:"Por favor ingrese un país válido.",
	PO_emptyError_vatNumber:"Por favor ingrese un número válido.",
	PO_PAY_lenError_contactName:"El nombre no puede exceder los 30 caracteres.",
	PO_PAY_lenError_lastName:"El apellido no puede exceder los 30 caracteres.",
	PO_PAY_lenError_addressline1:"La dirección 1 no puede exceder los 400 caracteres.",
	PO_PAY_lenError_addressline2:"La dirección 2 no puede exceder los 400 caracteres.",
	PO_PAY_lenError_state1:"Limitado a 40 caracteres.",
	PO_PAY_lenError_city:"Limitado a 400 caracteres.",
	PO_PAY_lenError_postalcode:"El largo del código postal debe de ser entre 4 y 10.",
	PO_lenError_tel:"El largo del numero de teléfono debe de ser entre 4 y 20.",
	PO_PAY_resError_contactName_21:"El nombre es necesario.",
	PO_PAY_resError_contactName_22:"El nombre excede el máximo de 100.",
	PO_PAY_resError_lastName_23:"El apellido es necesario.",
	PO_PAY_resError_lastName_24:"El apellido excede máximo de 100.",
	PO_PAY_resError_addressline1_31:"La dirección 1 es obligatoria.",
	PO_PAY_resError_addressline1_32:"La dirección 1 excede el máximo de 400.",
	PO_PAY_resError_addressline2_42:"La dirección 2  excede el máximo de 400.",
	PO_PAY_resError_city_51:"La ciudad es necesaria.",
	PO_PAY_resError_city_52:"El nombre de la ciudad excede el máximo de 400.",
	PO_PAY_resError_state_61:"Estado / provincia es necesario.",
	PO_PAY_resError_state_62:"El estado / provincia excede el máximo de 40.",
	PO_PAY_resError_country_71:"El país es necesario.",
	PO_PAY_resError_country_72:"El país excede el máximo de 100.",
	PO_PAY_resError_postalcode_81:"El código postal es necesario.",
	PO_PAY_resError_postalcode_82:"El código postal excede el máximo de 20.",
	PO_PAY_resError_tel_91:"El número de teléfono es necesario.",
	PO_PAY_resError_tel_92:"El número de teléfono excede el máximo de 20.",
	PO_resError_1:"La observación es invalida.",
	PO_resError_1002:"No se ha podido añadir el cupón.",
	PO_resError_3:"Cupón inválido.",
	PO_resError_4:"¡Felicitaciones!",
	PO_cannot_shipping_to:"A la dirección de envío que has elegido no se puede enviar, por favor ingrese una nueva dirección.",
	PO_only:"Solamente",
	PO_to:"a",
	PO_is_allow:"Es permitido",
	PO_number_allow:"Solamente se permiten numeros.",
	PO_enter_coupon:"Por favor ingrese un cupón.",
	PAY_success_dialog:"Sigue tu compra y realiza un próxima compra de manera más rápida y fácil. ¡Prueba nuestra nueva aplicación!",
	PAY_for_order:"Pagar por orden",
	PAY_error_11:"La clave debe de tener de 6 a 20 dígitos.",
	PAY_error_21:"Por favor ingrese un número de tarjeta válido.",
	PAY_error_22:"El número de tarjeta no debe de exceder lo 18 dígitos.",
	PAY_error_31:"El número de verificación de la tarjeta debe ser de 3 dígitos.",
	PAY_error_32:"El número de verificación de la tarjeta debe ser de 3 o 4 dígitos.",
	PAY_error_3:"El número de tarjeta es incorrecto.",
	PAY_error_2:"El código de seguridad no es correcto.",
	PAY_edit:"Editar",
	PAY_save:"Guardar",
	DETAIL_quntity_mininum_MOrder:"La cantidad no puede exceder la cantidad mínima. (Cantidad mínima:",
	DETAIL_quntity_mininum_MSstock:"La cantidad no puede exceder el stock máximo ",
	DETAIL_Show_more_photos:"Mostrar 10 fotos más",
	DETAIL_add_to_cart:"Un artículo agregado a la cesta de compra.",
	DETAIL_by:"Por",
	DETAIL_report_review:"Reportar esta crítica",
	DETAIL_seller_res:"Respuesta del vendedor",
	DETAIL_cannot_shipping_toL:"Este artículo no puede ser enviado a ",
    DETAIL_error1:"Por favor, seleccione opciones",
	CART_remove:"¿Eliminar del carrito?",
	LOGIN_6_30_characters:"Son requeridos de 6 a 20 caracteres.",
	Recommended_products:"Productos Recomendados",
	Show_more:"Ver más",
	Youmaylike:"Le podría interesar",
	COMMON_Price_onapp:"Compre con precio bajo en app！",
	UserType:"Por favor, seleccione por lo menos una opción."
};