/**
 * Created by zhaojing1 on 2015/1/20.
 */
var msgObj={
	hello:"Olá",
	sign_out:"Terminar Sessão",
	close:"perto",
	cancel:"Cancelar",
	apply:"Aplicar",
	reset:"Restaurar",
	max:"Max",
	min:"Min",
	filter:"Filtros",
	cas:"Categorias",
	price:"Preço",
	less_than:"menos de",
	clear_history:"Limpar Histórico",
	input_key_word:"Por favor introduza uma palavra-chave.",
	hot_search:"Mais Procurados",
	free_shipping:"Frete gratuíto",
	wholesale:"Venda por atacado",
	reviews:"Críticas",
	l_best_match:"Melhor Correspondência",
	l_price_lth:"Preço: Baixo a Alto",
	l_price_htl:"Preço: Alto a Baixo",
	l_items_htl:"Artigos vendidos: Alto a Baixo",
	l_recent_list:"Recentemento Listados",
	l_feedback:"Feedback",
	l_all_cas:"Todas as Categorais",
	l_min_order:"Pedido Min",
	PO_PAY_enter_State:"Por favor introduza um Estado ou Província ou Região válidos.",
	PO_only_number:"Só números são permitidos.",
	PO_PAY_emptyError_contactName:"Por favor introduza o seu primeiro nome. Se tive um nome do meio, por favor inclua-o também com o seu primeiro nome.",
	PO_PAY_emptyError_lastName:"O último nome é requirido ou a entrega poderá falhar.",
	PO_PAY_emptyError_addressline1:"Por favor introduza um endereço válido na linha1.",
	PO_PAY_emptyError_city:"Por favor introduza uma Cidade/Vila de faturamente válidas.",
	PO_PAY_emptyError_postalcode:"Por favor intruduza um Código de Postal válido.",
	PO_PAY_emptyError_tel:"Por favor intruduza um Telefone válido.",
	PO_PAY_emptyError_country:"Por favor introduza um país válido.",
	PO_emptyError_vatNumber:"Por favor introduza um NIF válido.",
	PO_PAY_lenError_contactName:"O tamanho do Primeiro Nome tem de ser menos de 30.",
	PO_PAY_lenError_lastName:"O tamanha do Último Nome tem de ser menos de 30.",
	PO_PAY_lenError_addressline1:"O tamanha da Linha1 de Endereço tem de ser menos de 400.",
	PO_PAY_lenError_addressline2:"O tamanha da Linha2 de Endereço tem de ser menos de 400.",
	PO_PAY_lenError_state1:"Limitado a 40 caractéres.",
	PO_PAY_lenError_city:"Limitado a 400 caractéres.",
	PO_PAY_lenError_postalcode:"La longueur du code postal doit être compris entre 4 et 10.",
	PO_lenError_tel:"La longueur du numéro de téléphone doit être compris entre 4 et 20.",
	PO_PAY_resError_contactName_21:"Primeiro Nome é requirido.",
	PO_PAY_resError_contactName_22:"O tamanho do Primeiro Nome excedeu o Máximo de 100.",
	PO_PAY_resError_lastName_23:"O Último Nome é requirido.",
	PO_PAY_resError_lastName_24:"O tamanho do Último Nome excedeu o Máximo de 100.",
	PO_PAY_resError_addressline1_31:"Linha de Endereço1 é requirida.",
	PO_PAY_resError_addressline1_32:"O tamanho da Linha1 de Endereço excedeu o máximo de 400.",
	PO_PAY_resError_addressline2_42:"O tamanho da Linha2 de Endereço excedeu o máximo de 400.",
	PO_PAY_resError_city_51:"Cidade é requirida.",
	PO_PAY_resError_city_52:"O tamanho da Cidade excede o máximo de 400.",
	PO_PAY_resError_state_61:"Estado/Província é requirido.",
	PO_PAY_resError_state_62:"O tamanho de Estado/Província excede o max 40.",
	PO_PAY_resError_country_71:"País é requirido.",
	PO_PAY_resError_country_72:"O tamanho do País excedeu o max 100.",
	PO_PAY_resError_postalcode_81:"Código Postal é requirido.",
	PO_PAY_resError_postalcode_82:"O tamanho do Código Postal excedeu o máximo de 20.",
	PO_PAY_resError_tel_91:"Número de Telefone é requirido.",
	PO_PAY_resError_tel_92:"O tamanho do número de telefone excedeu o máximo de 20.",
	PO_resError_1:"Notificação Inválida",
	PO_resError_1002:"Não pode adicionar cupão",
	PO_resError_3:"Cupão Inválido",
	PO_resError_4:"Parabéns!",
	PO_cannot_shipping_to:"O seu endereço de entrega escolhido não pode receber entregas, por favor escolha um novo endereço.",
	PO_only:"Apenas",
	PO_to:"para",
	PO_is_allow:"é permitido",
	PO_number_allow:"Só números são permitidos.",
	PO_enter_coupon:"Por favor introduza um Cupão.",
	PAY_success_dialog:"Siga a sua compra e torne a sua experiência mais rápida e simples. Experimente a nossa nova App!",
	PAY_for_order:"Pagar pelo Pedido",
	PAY_error_11:"A Palavra-Passe tem de ter entre 6 e 20 dígitos.",
	PAY_error_21:"Por favor introduza um número de cartão válido.",
	PAY_error_22:"O número de verificação do cartão tem de ter menos de 18 dígitos.",
	PAY_error_31:"O número de verificação do cartão tem de ter 3 dígitos.",
	PAY_error_32:"O número de verificação do cartão tem de ter 3 ou 4 dígitos.",
	PAY_error_3:"Nº do Cartão está incorrecto.",
	PAY_error_2:"Código de Segurança está incorrecto.",
	PAY_edit:"Editar",
	PAY_save:"Salvar",
	DETAIL_quntity_mininum_MOrder:"A quantidade não pode exceder o pedido mínimo (Pedido Min.",
	DETAIL_quntity_mininum_MSstock:"A quantidade não pode exceder o stock máximo (Max. Stock= ",
	DETAIL_Show_more_photos:"Mostrar mais 10 fotos",
	DETAIL_add_to_cart:"1 artigo adicionado ao carrinho",
	DETAIL_by:"De",
	DETAIL_report_review:"Reportar Estaa Crítica",
	DETAIL_seller_res:"Resposta do Vendedor",
	DETAIL_cannot_shipping_toL:"Este artigo nao pode ser expedido para ",
    DETAIL_error1:"Selecione as opções",
	CART_remove:"Remover do carrinho?",
	LOGIN_6_30_characters:"6-30 caractéres requiridos",
	Recommended_products:"Produtos Recomendados",
	Show_more:"Veja Mais",
	Youmaylike:"Você pode gostar",
	COMMON_Price_onapp:"Compre com preço justo na App!",
	UserType:"Escolha pelo menos uma opção."
};