/**
 * Created by zhaojing1 on 2015/1/20.
 */
var msgObj={
	Head_not: "Değil",
    Head_signIn: "Giriş yapın",
    Head_joinFree: "Ücretsiz Katılın",
    Head_home: "Ana Sayfa",
    Head_selectLanguage: "Dil Seçin",
    Head_downloadApp: "Uygulamayı İndirin",
	Head_feedback: "Geri Bildirim",
    Head_or: "veya",
    Head_shoppingCart: "Alışveriş Sepeti",
    Head_myDHgate: "DHgate Hesabım",
    Head_myCoupons: "Kuponlarım",
    Head_myFavorites: "Favorilerim",
    Head_myMessage: "Mesajlarım",
    Head_myVipClub: "VIP Kulübüm",
    Head_myOrders: "Siparişlerim",
    Head_mainMenu: "Ana Menü",
    Head_shoppingFor:"Aradığım ürün: ",
    Home_dailyDeals: "Günlük Teklifler",
    Home_seeAll: "Tümünü gör",
    hello:"Merhaba",
    sign_out:"Çıkış yap",
    close:"Kapat",
    cancel:"İptal",
    apply:"Uygula",
    reset:"Sıfırla",
    max:"Maksimum",
    min:"Minimum",
    filter:"Filtrele",
    cas:"Kategoriler",
    price:"Fiyat",
    less_than:"şundan az:",
    clear_history:"Geçmişi temizle",
    input_key_word:"Lütfen anahtar sözcük girin.",
    hot_search:"Son Aramalar",
    free_shipping:"Ücretsiz Gönderim",
    wholesale:"Toptan Satış",
    reviews:"İncelemeler",
    ok:"tamam",
    please_wait:"Lütfen bekleyin.",
    l_best_match:"En İyi Eşleşme",
    l_price_lth:"Fiyat: Düşükten Yükseğe",
    l_price_htl:"Fiyat: Yüksekten Düşüğe",
    l_items_htl:"Satılan Ürünler: Yüksekten Düşüğe",
    l_recent_list:"Yeni Eklenen",
    l_feedback:"Geri Bildirim",
    l_all_cas:"Tüm Kategoriler",
    l_min_order:"Minimum Sipariş",
    PO_PAY_enter_State:"Lütfen geçerli bir Eyalet, İl veya Bölge girin.",
    PO_only_number:"Yalnızca Rakamlara izin verilir.",
    PO_PAY_emptyError_contactName:"Lütfen adınızı girin. Varsa ikinci adınızı da lütfen ilk adınızla birlikte girin.",
    PO_PAY_emptyError_lastName:"Soyad girmek gereklidir, yoksa teslimat başarısız olabilir.",
    PO_PAY_emptyError_addressline1:"Lütfen geçerli bir 1. Adres Satırı girin.",
    PO_PAY_emptyError_city:"Lütfen geçerli bir Fatura Şehri/Beldesi girin.",
    PO_PAY_emptyError_postalcode:"Lütfen geçerli bir Posta Kodu girin.",
    PO_PAY_emptyError_tel:"Lütfen geçerli bir Telefon girin.",
    PO_PAY_emptyError_country:"Lütfen geçerli bir Ülke girin.",
    PO_emptyError_vatNumber:"Lütfen geçerli bir KDV Numarası girin.",
    PO_PAY_lenError_contactName:"Ad uzunluğu 30 karakterden az olmalıdır.",
    PO_PAY_lenError_lastName:"Soyad uzunluğu 30 karakterden az olmalıdır.",
    PO_PAY_lenError_addressline1:"1. Adres Satırı uzunluğu 400 karakterden az olmalıdır.",
    PO_PAY_lenError_addressline2:"2. Adres Satırı uzunluğu 400 karakterden az olmalıdır.",
    PO_PAY_lenError_state1:"40 karakterle sınırlıdır.",
    PO_PAY_lenError_city:"400 karakterle sınırlıdır.",
    PO_PAY_lenError_postalcode:"Posta Kodu uzunluğu 4 ile 10 arasında olmalıdır.",
    PO_lenError_tel:"Posta Kodu uzunluğu 4 ile 20 arasında olmalıdır.",
    PO_PAY_resError_contactName_21:"Ad girmek gereklidir.",
    PO_PAY_resError_contactName_22:"Ad uzunluğu 100 karakteri geçemez.",
    PO_PAY_resError_lastName_23:"Soyad girmek gereklidir.",
    PO_PAY_resError_lastName_24:"Soyad uzunluğu 100 karakteri geçemez.",
    PO_PAY_resError_addressline1_31:"1. Adres Satırı gereklidir.",
    PO_PAY_resError_addressline1_32:"1. Adres Satırı uzunluğu 400 karakteri geçemez.",
    PO_PAY_resError_addressline2_42:"2. Adres Satırı uzunluğu 400 karakteri geçemez.",
    PO_PAY_resError_city_51:"Şehir girmek gereklidir.",
    PO_PAY_resError_city_52:"Şehir uzunluğu 400 karakteri geçemez.",
    PO_PAY_resError_state_61:"Eyalet / İl girmek gereklidir.",
    PO_PAY_resError_state_62:"Eyalet / İl uzunluğu 40 karakteri geçemez.",
    PO_PAY_resError_country_71:"Ülke girmek gereklidir.",
    PO_PAY_resError_country_72:"Ülke uzunluğu 100 karakteri geçemez.",
    PO_PAY_resError_postalcode_81:"Posta Kodu girmek gereklidir.",
    PO_PAY_resError_postalcode_82:"Posta Kodu uzunluğu 20 karakteri geçemez.",
    PO_PAY_resError_tel_91:"Telefon Numarası girmek gereklidir.",
    PO_PAY_resError_tel_92:"Telefon Numarası uzunluğu 20 karakteri geçemez.",
    PO_resError_1:"Geçersiz Görüş",
    PO_resError_1002:"Kupon eklenemedi",
    PO_resError_3:"Geçersiz kupon",
    PO_resError_4:"Tebrikler!",
    PO_cannot_shipping_to:"Gönderim yapılamayan bir teslimat adresi girdiniz, lütfen yeni bir adres girin.",
    PO_only:"Yalnızca",
    PO_to:"şuraya",
    PO_is_allow:"izin verilir",
    PO_number_allow:"Yalnızca Rakamlara izin verilir.",
    PO_enter_coupon:"Lütfen Kupon girin.",
    PAY_success_dialog:"Satın aldıklarınızı takip edin ve sonraki alışveriş deneyiminizi hızlandırın ve kolaylaştırın. Yepyeni uygulamamızı deneyin!",
    PAY_for_order:"Sipariş Ödemesi",
    PAY_error_11:"Parola 6 ile 20 rakam arasında olmalıdır.",
    PAY_error_21:"Lütfen geçerli bir Kart Numarası girin.",
    PAY_error_22:"Kart numarası 18 rakamdan az olmalıdır.",
    PAY_error_31:"Kart Doğrulama Numarası 3 rakamdan oluşmalıdır.",
    PAY_error_32:"Kart Doğrulama Numarası 3 veya 4 rakamdan oluşmalıdır.",
    PAY_error_3:"Kart Numarası yanlış.",
    PAY_error_2:"Güvenlik Kodu yanlış.",
    PAY_edit:"Düzenle",
    PAY_save:"Kaydet",
    DETAIL_quntity_mininum_MOrder:"Miktar, minimum sipariş değerini aşamaz. (Min. Sipariş =",
    DETAIL_quntity_mininum_MSstock:"Miktar, maksimum stok değerini aşamaz (Maks. Stok = ",
    DETAIL_Show_more_photos:"10 fotoğraf daha göster",
    DETAIL_add_to_cart:"1 ürün sepete eklendi",
	DETAIL_add_choose_cart:"Please choose itemSku",
    DETAIL_by:"Tarafından",
    DETAIL_report_review:"Bu İncelemeyi Şikayet Edin",
    DETAIL_seller_res:"Satıcı yanıtı",
    DETAIL_cannot_shipping_toL:"Bu ürün şu ülkeye gönderilemiyor: ",
    DETAIL_error1:"Lütfen seçenek belirleyin.",
    UserType:"Lütfen en az bir seçenek belirleyin.",
    CART_remove:"Sepetten kaldırılsın mı?",
    Recommended_products:"Önerilen Ürünler",
    Show_more:"Daha Fazla Göster",
    Youmaylike:"Şunları beğenebilirsiniz",
    COMMON_Price_onapp:"Uygulamaya Özel Uygun Fiyatlar!",
    LOGIN_6_30_characters:"6--30 karakter gereklidir.",
    Cart_Back:"Geri",
    Cart_my_cart:"Sepetim",
    Cart_items_subtotal:"ürün Ara Toplam",
    Cart_check_out:"Ödeme yap",
    Cart_alert_noitem:"Alışveriş sepetinizde ürün bulunmamaktadır",
    Continue_shopping:"Alışverişe Devam Et",
    PO_item_sold_out:"Ürün tükendi",
    FAV_title:"Favorilerim",
    FAV_sold_out:"Tükendi",
    FAV_not_available:"Mevcut Değil",
    FAV_loading:"Yükleniyor***",
    FAV_removed_text:"Ürün listeden kaldırıldı.",
    FAV_off_vip:"VIP Fiyatlarda {{v}} İNDİRİM",
    FAV_off:"{{v}} İNDİRİM",
    FAV_undo:"geri al",
    FAV_noItem:"Favori listenizde ürün bulunmamaktadır",
    min_order:"Minimum Sipariş",
    //'0':折扣,'1':直降,'2':vip+促销,'3':vip+直降,'4':vip
    COMMON_Discount_0:"${val}% İndirim",
    COMMON_Discount_1:"$${val} İndirim",
    COMMON_Discount_2:"${val}% İndirim Artı",
    COMMON_Discount_3:"$${val} İndirim Artı",
    COMMON_Discount_4:"VIP"
};