/**
 * Created by zhaojing1 on 2015/1/20.
 */
var msgObj={
	hello:"Здравствуйте",
	sign_out:"выход",
	close:"близко",
	cancel:"отменить",
	apply:"Применить",
	reset:"Сброс",
	max:"Максимум",
	min:"Минимум",
	filter:"Фильтр",
	cas:"Категории",
	price:"Цена",
	less_than:"меньше чем",
	clear_history:"Очистить историю",
	input_key_word:"Пожалуйста, введите ключевое слово.",
	hot_search:"Популярные запросы",
	free_shipping:"Бесплатная доставка",
	wholesale:"Оптом",
	reviews:"Отзывы",
	l_best_match:"Лучшее соответствие",
	l_price_lth:"Цена:от низкой до высокой",
	l_price_htl:"Цена:от высокой до низкой",
	l_items_htl:"Проданные товары:от высокой до низкой",
	l_recent_list:"Недавно добавленные",
	l_feedback:"Отзывы",
	l_all_cas:"Все категории",
	l_min_order:"Минимальный заказ",
	PO_PAY_enter_State:"Пожалуйста, введите действительный  регион/область.",
	PO_only_number:"Допускаются только цифры.",
	PO_PAY_emptyError_contactName:"Пожалуйста, введите ваше имя. Отчество по желанию.",
	PO_PAY_emptyError_lastName:"Требуется фамилия или товар рискует быть не доставлен.",
	PO_PAY_emptyError_addressline1:"Пожалуйста, введите действительный адрес.",
	PO_PAY_emptyError_city:"Пожалуйста, введите действительную платежную городу.",
	PO_PAY_emptyError_postalcode:"Пожалуйста, введите действительный почтовы индекс.",
	PO_PAY_emptyError_tel:"Пожалуйста, введите действительный номер телефона.",
	PO_PAY_emptyError_country:"Пожалуйста, введите действительную страну.",
	PO_emptyError_vatNumber:"Пожалуйста, введите действительный номер НДС.",
	PO_PAY_lenError_contactName:"Имя не должно превышать 30 символов.",
	PO_PAY_lenError_lastName:"Фамилия не должна превышать 30 символов.",
	PO_PAY_lenError_addressline1:"Длина адреса 1 не может превышать 400 символов.",
	PO_PAY_lenError_addressline2:"Длина адреса 2 не может превышать 400 символов.",
	PO_PAY_lenError_state1:"Ограничено до 40 символов.",
	PO_PAY_lenError_city:"LОграничено до 400 символов.",
	PO_PAY_lenError_postalcode:"Длина почтового индекса составляет от 4 до 10.",
	PO_lenError_tel:"Длина номера телефона составляет от 4 до 20.",
	PO_PAY_resError_contactName_21:"Введите имя.",
	PO_PAY_resError_contactName_22:"Имя не должно превышать 100 символов.",
	PO_PAY_resError_lastName_23:"Введите фамилию .",
	PO_PAY_resError_lastName_24:"Фамилия не должна превышать 100 символов.",
	PO_PAY_resError_addressline1_31:"Введите адрес 1.",
	PO_PAY_resError_addressline1_32:"Длина адреса 1 не может превышать 400 символов.",
	PO_PAY_resError_addressline2_42:"Длина адреса 1 не может превышать 401 символов.",
	PO_PAY_resError_city_51:"Введите название города.",
	PO_PAY_resError_city_52:"Название города не должно превышать больше 400 символов.",
	PO_PAY_resError_state_61:"Введите название области.",
	PO_PAY_resError_state_62:"Название области не должно превышать больше 40 символов.",
	PO_PAY_resError_country_71:"Введите название страны.",
	PO_PAY_resError_country_72:"Название страны не должно превышать 100 символов.",
	PO_PAY_resError_postalcode_81:"Введите почтовый индекс.",
	PO_PAY_resError_postalcode_82:"Длина почтового индекса не должна превышать 20 символов.",
	PO_PAY_resError_tel_91:"Введите номер телефона.",
	PO_PAY_resError_tel_92:"Длина номера телефона не должна превышать 20 символов.",
	PO_resError_1:"Недействительный комментарий",
	PO_resError_1002:"Не удалось добавить купон",
	PO_resError_3:"Недействительный купон",
	PO_resError_4:"Поздравляем!",
	PO_cannot_shipping_to:"К сожалению мы не можем доставить заказ по этому адресу, пожалуйста, введите другой адрес.",
	PO_only:"Только",
	PO_to:"-",
	PO_is_allow:"разрешено",
	PO_number_allow:"Допускаются только цифры.",
	PO_enter_coupon:"Пожалуйста, введите купон.",
	PAY_success_dialog:"Отслеживайте вашу покупку и сделайте следующий заказ быстрее и легче, попробовав наше новое приложе!",
	PAY_for_order:"Оплатить заказ",
	PAY_error_11:"Введите пароль от 6 до 20 цифр.",
	PAY_error_21:"Пожалуйста, введите действительный номер карты.",
	PAY_error_22:"Номер карты не может быть меньше 18 цифр.",
	PAY_error_31:"Длина контрольного номера карты состоит из 3 цифр.",
	PAY_error_32:"Длина контрольного номера карты состоит из 3 или 4 цифр.",
	PAY_error_3:"Неправильный номер карты.",
	PAY_error_2:"Неправильный контрольный номер карты.",
	PAY_edit:"Изменить",
	PAY_save:"Экономить",
	DETAIL_quntity_mininum_MOrder:"Количество не может превышать минимальный заказ (Минимальный заказ=",
	DETAIL_quntity_mininum_MSstock:"The quantity can't exceed the maximum stock (Max. Stock = ",
	DETAIL_Show_more_photos:"Показать еще 10 фото",
	DETAIL_add_to_cart:"1 товар добавлен в корзину",
	DETAIL_by:"",
	DETAIL_report_review:"Пожаловаться на этот отзыв",
	DETAIL_seller_res:"Ответ продавца",
	DETAIL_cannot_shipping_toL:"Этот объект нельзя доставлять до ",
    DETAIL_error1:"Пожалуйста, выберите параметры",
	CART_remove:"Удалить из корзины?",
	LOGIN_6_30_characters:"требуется 6-30 символов.",
	Recommended_products:"Рекомендуемые",
	Show_more:"Показать Еще",
	Youmaylike:"Вам могут понравиться",
	COMMON_Price_onapp:"Получите более низкие цены на App!",
	UserType:"Пожалуйста, выберите минимум один параметр"
};