/**
 * Created by zhaojing1 on 2015/1/20.
 */
var msgObj={
	hello:"Hello",
	sign_out:"Sign out",
	close:"Close",
	cancel:"Cancel",
	apply:"Apply",
	reset:"Reset",
	max:"Max",
	min:"Min",
	filter:"Filter",
	cas:"Categories",
	price:"Price",
	less_than:"less than",
	clear_history:"Clear history",
	input_key_word:"Please input a keyword.",
	hot_search:"Hot Searches",
	free_shipping:"Free Shipping",
	wholesale:"Wholesale",
	reviews:"Reviews",
	l_best_match:"Best Match",
	l_price_lth:"Price: Low to High",
	l_price_htl:"Price: High to Low",
	l_items_htl:"Items Sold: High to Low",
	l_recent_list:"Recently Listed",
	l_feedback:"Feedback",
	l_all_cas:"All Categories",
	l_min_order:"Min Order",
	PO_PAY_enter_State:"Please enter a valid State or Province or Region.",
	PO_only_number:"Only Numbers allowed.",
	PO_PAY_emptyError_contactName:"Please enter your first name. If you have a middle name, please also include it with your first name.",
	PO_PAY_emptyError_lastName:"Last name is required or delivery could fail.",
	PO_PAY_emptyError_addressline1:"Please enter a valid Address Line1.",
	PO_PAY_emptyError_city:"Please enter a valid Billing City/Town.",
	PO_PAY_emptyError_postalcode:"Please enter a valid Postal Code.",
	PO_PAY_emptyError_tel:"Please enter a valid Telephone.",
	PO_PAY_emptyError_country:"Please enter a valid Country.",
	PO_emptyError_vatNumber:"Please enter a valid vatNumber.",
	PO_PAY_lenError_contactName:"The length of First Name must less than 30.",
	PO_PAY_lenError_lastName:"The length of Last Name must less than 30.",
	PO_PAY_lenError_addressline1:"The length of Address Line1 must less than 400.",
	PO_PAY_lenError_addressline2:"The length of Address Line2 must less than 400.",
	PO_PAY_lenError_state1:"Limited to 40 characters.",
	PO_PAY_lenError_city:"Limited to 400 characters.",
	PO_PAY_lenError_postalcode:"The length of Postal Code must between 4 and 10.",
	PO_lenError_tel:"The length of Telephone must between 4 and 20.",
	PO_PAY_resError_contactName_21:"First name is required.",
	PO_PAY_resError_contactName_22:"The length of First Name exceed max 100.",
	PO_PAY_resError_lastName_23:"Last Name name is required.",
	PO_PAY_resError_lastName_24:"The length of Last Name exceed max 100.",
	PO_PAY_resError_addressline1_31:"Address Line1 is required.",
	PO_PAY_resError_addressline1_32:"The length of Address Line1 exceed max 400.",
	PO_PAY_resError_addressline2_42:"The length of Address Line2 exceed max 400.",
	PO_PAY_resError_city_51:"City is required.",
	PO_PAY_resError_city_52:"The length of City exceed max 400.",
	PO_PAY_resError_state_61:"State / Province is required.",
	PO_PAY_resError_state_62:"The length of State / Province exceed max 40.",
	PO_PAY_resError_country_71:"Country is required.",
	PO_PAY_resError_country_72:"The length of Country exceed max 100.",
	PO_PAY_resError_postalcode_81:"Postal/Zip Code is required.",
	PO_PAY_resError_postalcode_82:"The length of Postal/Zip Code exceed max 20.",
	PO_PAY_resError_tel_91:"Phone Number is required.",
	PO_PAY_resError_tel_92:"The length of Phone Number exceed max 20.",
	PO_resError_1:"Invalid Remark",
	PO_resError_1002:"Could not add coupon",
	PO_resError_3:"Invalid coupon",
	PO_resError_4:"Congratulations!",
	PO_cannot_shipping_to:"You choosed shipping address cannot shipped to,please enter a new address.",
	PO_only:"Only",
	PO_to:"to",
	PO_is_allow:"is allowed",
	PO_number_allow:"Only Numbers allowed.",
	PO_enter_coupon:"Please enter a Coupon.",
	PAY_success_dialog:"Track your purchase and make your next shopping experience faster and easier. Try our brand new app!",
	PAY_for_order:"Pay For Order",
	PAY_error_11:"The password must be between 6 to 20 digits.",
	PAY_error_21:"Please enter a valid Card Number.",
	PAY_error_22:"The card number must be less than 18 digits.",
	PAY_error_31:"The length of Card Verification Number must be 3 digits.",
	PAY_error_32:"The length of Card Verification Number must be 3 or 4 digits.",
	PAY_error_3:"Card No is incorrect.",
	PAY_error_2:"Security Code is incorrect.",
	PAY_edit:"Edit",
	PAY_save:"Save",
	DETAIL_quntity_mininum_MOrder:"The quantity can't exceed the minimum order (Min. Order =",
	DETAIL_quntity_mininum_MSstock:"The quantity can't exceed the maximum stock (Max. Stock = ",
	DETAIL_Show_more_photos:"Show 10 more photos",
	DETAIL_add_to_cart:"1 item added to cart",
	DETAIL_add_choose_cart:"Please choose itemSku",
	DETAIL_by:"By",
	DETAIL_report_review:"Report This Review",
	DETAIL_seller_res:"Seller response",
	DETAIL_cannot_shipping_toL:"This item cannot be shipped to ",
    DETAIL_error1:"Please select options",
	CART_remove:"Remove from cart?",
	LOGIN_6_30_characters:"6-30 characters required.",
	Recommended_products:"Recommended Products",
	Show_more:"Show More",
   	Youmaylike:"You may like",
    COMMON_Price_onapp:"Shop Better Prices on the App!",
    UserType:"Please choose at least one option."
};