/**
 * Created by zhaojing1 on 2015/1/20.
 */
var msgObj={
	hello:"Bonjour",
	sign_out:"Se Déconnecter",
	close:"près",
	cancel:"Annuler",
	apply:"Confirmer",
	reset:"Reset",
	max:"Max",
	min:"Min",
	filter:"Filtres",
	cas:"Catégories",
	price:"Prix",
	less_than:"Inférieur à",
	clear_history:"Effacer l'historique",
	input_key_word:"Mot-clé.",
	hot_search:"Les plus recherchés",
	free_shipping:"Livraison gratuite",
	wholesale:"Vente en gros",
	reviews:"Examen",
	l_best_match:"Meilleurs résultats",
	l_price_lth:"Prix: Moins à Plus",
	l_price_htl:"Prix: Plus à Moins",
	l_items_htl:"Articles vendus: du Plus au Moins",
	l_recent_list:"Article récent",
	l_feedback:"Avis",
	l_all_cas:"Toutes les catégories",
	l_min_order:"Commande minimum",
	PO_PAY_enter_State:"Veuillez rentrer une ville, région ou département valide.",
	PO_only_number:"Chiffres uniquement.",
	PO_PAY_emptyError_contactName:"Veuillez rentrer votre prénom. Si vous avez un deuxième prénom, merci de le renseigner avec le prénom.",
	PO_PAY_emptyError_lastName:"Le nom est requis pour assurer la livraison.",
	PO_PAY_emptyError_addressline1:"Veuillez entrer une adresse valide Ligne 1.",
	PO_PAY_emptyError_city:"Veuillez entrer une ville de facturation valide.",
	PO_PAY_emptyError_postalcode:"Veuillez entrer un code postal valide.",
	PO_PAY_emptyError_tel:"Veuillez entrer un numéro de téléphone valide",
	PO_PAY_emptyError_country:"Veuillez rentrer un pays valide.",
	PO_emptyError_vatNumber:"Veuillez rentrer un code TVA valide.",
	PO_PAY_lenError_contactName:"La longueur du prénom doit être inférieure à 30.",
	PO_PAY_lenError_lastName:"La longueur du nom doit être inférieure à 30.",
	PO_PAY_lenError_addressline1:"La longueur de Adresse1 doit être inférieure à 400.",
	PO_PAY_lenError_addressline2:"La longueur de Adresse2 doit être inférieure à 400.",
	PO_PAY_lenError_state1:"Limité à 40 caractères.",
	PO_PAY_lenError_city:"Limité à 400 caractères.",
	PO_PAY_lenError_postalcode:"La longueur du code postal doit être compris entre 4 et 10.",
	PO_lenError_tel:"La longueur du numéro de téléphone doit être compris entre 4 et 20.",
	PO_PAY_resError_contactName_21:"Prénom requis.",
	PO_PAY_resError_contactName_22:"Le prénom dépasse la longueur max 100.",
	PO_PAY_resError_lastName_23:"Nom de famille requis.",
	PO_PAY_resError_lastName_24:"Le nom de famille dépasse la longueur max 100.",
	PO_PAY_resError_addressline1_31:"Adresse ligne1 requis",
	PO_PAY_resError_addressline1_32:"L'adresse ligne1 dépasse la longueur max 400.",
	PO_PAY_resError_addressline2_42:"L'adresse ligne2 dépasse la longueur max 400.",
	PO_PAY_resError_city_51:"La ville est requise.",
	PO_PAY_resError_city_52:"La ville dépasse la longueur max 400.",
	PO_PAY_resError_state_61:"Ville/Département requis.",
	PO_PAY_resError_state_62:"La ville/département dépasse la longueur max 40.",
	PO_PAY_resError_country_71:"Pays requis.",
	PO_PAY_resError_country_72:"Le pays dépasse la longueur max 100.",
	PO_PAY_resError_postalcode_81:"Code postal requis.",
	PO_PAY_resError_postalcode_82:"Le code postal dépasse la longueur max 20.",
	PO_PAY_resError_tel_91:"Numéro de téléphone requis.",
	PO_PAY_resError_tel_92:"Le numéro de téléphone dépasse la longueur max 20.",
	PO_resError_1:"Remarque invalide",
	PO_resError_1002:"Le coupon n'a pu être ajouté",
	PO_resError_3:"Coupon invalide",
	PO_resError_4:"Félicitations!",
	PO_cannot_shipping_to:"Nous ne pouvons livrer à cette adresse, veuillez rentrer une nouvelle adresse.",
	PO_only:"Seulement",
	PO_to:"à",
	PO_is_allow:"est accepté",
	PO_number_allow:"Chiffres uniquement.",
	PO_enter_coupon:"Veuillez rentrer un coupon.",
	PAY_success_dialog:"Suivez votre commande et rendez votre experience shopping plsu rapide et plus facile. Essayez notre nouvelle application!",
	PAY_for_order:"Payer la commande",
	PAY_error_11:"Le mote de passe doit être compris entre 6 et 20 caractères.",
	PAY_error_21:"Veuillez rentrer un numéro de carte vailde.",
	PAY_error_22:"Le numéro de carte doit être inférieur à 18 chiffres.",
	PAY_error_31:"Le code de sécurité doit être à 3 chiffres.",
	PAY_error_32:"Le code de sécurité doit être à 3 ou 4 chiffres.",
	PAY_error_3:"Numéro de carte incorrect.",
	PAY_error_2:"Code de sécurité incorrect.",
	PAY_edit:"Modifier",
	PAY_save:"Enregistrer",
	DETAIL_quntity_mininum_MOrder:"La quantité ne peut excéder la commande minimum (Commande Min. =",
	DETAIL_quntity_mininum_MSstock:"La quantité ne peut dépasser le stock maximum (Stock Max. = ",
	DETAIL_Show_more_photos:"Montrer 10 autres photos",
	DETAIL_add_to_cart:"Un article a été ajouté au panier",
	DETAIL_by:"Par",
	DETAIL_report_review:"Dénoncer cet avis",
	DETAIL_seller_res:"Réponse du vendeur",
	DETAIL_cannot_shipping_toL:"Cet article ne peut être livré à ",
    DETAIL_error1:"Veuillez sélectionner les options",
	CART_remove:"Retirer du panier?",
	LOGIN_6_30_characters:"6-30 caractères requis",
	Recommended_products:"Produits recommandés",
	Show_more:"En savoir plus",
	Youmaylike:"Vous aimeriez",
	COMMON_Price_onapp:"Acheter au meilleur prix sur APP !",
	UserType:"Veuillez choisir au moins une option."
};