/**
 * Created by zhaojing1 on 2015/1/20.
 */
var msgObj={
	hello:"Ciao",
	sign_out:"Esci",
	close:"vicino",
	cancel:"Cancella",
	apply:"Applica",
	reset:"Resetta",
	max:"Max",
	min:"Min",
	filter:"Filtro",
	cas:"Categorie",
	price:"Prezzo",
	less_than:"meno di",
	clear_history:"Cancella cronologia",
	input_key_word:"Digita una parola chiave.",
	hot_search:"Ricerche Popolari",
	free_shipping:"Spedizione gratuita",
	wholesale:"Commercio all'ingrosso",
	reviews:"Recensioni",
	l_best_match:"Miglior Abbinamento",
	l_price_lth:"Prezzo: Crescente",
	l_price_htl:"Prezzo: Decrescente",
	l_items_htl:"Articoli Venduti: Decrescente",
	l_recent_list:"Elenchi Recenti",
	l_feedback:"Commento",
	l_all_cas:"Tutte le Categorie",
	l_min_order:"Ordine Minimo",
	PO_PAY_enter_State:"Inserisci uno Stato o Provincia o Regione valido.",
	PO_only_number:"Solo numeri consentiti.",
	PO_PAY_emptyError_contactName:"Inserisci il tuo nome. Se si dispone di un secondo nome, si prega di includerlo con il nome.",
	PO_PAY_emptyError_lastName:"Serve il cognome o la consegna potrebbe non riuscire.",
	PO_PAY_emptyError_addressline1:"Si prega di inserire una Riga di Indirizzo1 valida.",
	PO_PAY_emptyError_city:"Si prega di inserire una Città di Fatturazione valida.",
	PO_PAY_emptyError_postalcode:"Si prega di inserire un Codice Postale valido.",
	PO_PAY_emptyError_tel:"Immetti un numero di telefono valido.",
	PO_PAY_emptyError_country:"Inserisci un Paese valido.",
	PO_emptyError_vatNumber:"Inserisci un Numero di Partita IVA valido.",
	PO_PAY_lenError_contactName:"La lunghezza del Nome deve essere inferiore a 30.",
	PO_PAY_lenError_lastName:"La lunghezza del Cognome deve essere inferiore a 30.",
	PO_PAY_lenError_addressline1:"La lunghezza della  Riga di Indirizzo1 deve essere inferiore a 400.",
	PO_PAY_lenError_addressline2:"La lunghezza della Riga di Indirizzo2 deve essere inferiore a 400.",
	PO_PAY_lenError_state1:"Limitato a 40 caratteri.",
	PO_PAY_lenError_city:"Limitato a 400 caratteri.",
	PO_PAY_lenError_postalcode:"La lunghezza del Codice Postale deve essere compresa tra 4 e 10.",
	PO_lenError_tel:"La lunghezza del Telefono deve essere compresa tra 4 e 20.",
	PO_PAY_resError_contactName_21:"Il nome è richiesto.",
	PO_PAY_resError_contactName_22:"La lunghezza del Nome supera il massimo di 100.",
	PO_PAY_resError_lastName_23:"Il Cognome è richiesto.",
	PO_PAY_resError_lastName_24:"La lunghezza del Cognome supera il massimo di 100.",
	PO_PAY_resError_addressline1_31:"La Riga di Indirizzo1 è richiesta.",
	PO_PAY_resError_addressline1_32:"La lunghezza della Riga di Indirizzo1 supera il massimo di 400.",
	PO_PAY_resError_addressline2_42:"La lunghezza della Riga di Indirizzo2 supera il massimo di 400.",
	PO_PAY_resError_city_51:"La Città è richiesta.",
	PO_PAY_resError_city_52:"La lunghezza della Città  supera il massimo di 400.",
	PO_PAY_resError_state_61:"Lo Stato/Provincia è richiesto.",
	PO_PAY_resError_state_62:"La lunghezza dello Stato/Provincia supera il massimo di 40.",
	PO_PAY_resError_country_71:"Il Paese è richiesto.",
	PO_PAY_resError_country_72:"La lunghezza del Paese supera il massimo di 100.",
	PO_PAY_resError_postalcode_81:"Il Codice Postale è richiesto.",
	PO_PAY_resError_postalcode_82:"La lunghezza del Codice Postale supera il massimo di 20.",
	PO_PAY_resError_tel_91:"Il Numero di Telefono è richiesto.",
	PO_PAY_resError_tel_92:"La lunghezza del Numero di Telefono supera il massimo di 20.",
	PO_resError_1:"Nota Non Valida",
	PO_resError_1002:"Impossibile aggiungere buoni",
	PO_resError_3:"Buono Non Valido",
	PO_resError_4:"Congratulazioni!",
	PO_cannot_shipping_to:"Impossibile spedire all'indirizzo di spedizione selezionato, inserisci un nuovo indirizzo.",
	PO_only:"Solo",
	PO_to:"a",
	PO_is_allow:"è consentito",
	PO_number_allow:"Solo numeri consentiti.",
	PO_enter_coupon:"Inserisci un Buono.",
	PAY_success_dialog:"Monitora il tuo acquisto e rendi la tua prossima esperienza di acquisto più veloce e facile. Prova la nostra nuova app!",
	PAY_for_order:"Paga Ordine",
	PAY_error_11:"La password deve contenere tra 6 e 20 digit.",
	PAY_error_21:"Inserisci un Numero di Carta valido.",
	PAY_error_22:"Il numero di carta deve contenere meno di 18 digit.",
	PAY_error_31:"La lunghezza del CVV deve essere 3 digit.",
	PAY_error_32:"La lunghezza del CVV deve essere 3 o 4 digit.",
	PAY_error_3:"Il Numero di Carta non è corretto.",
	PAY_error_2:"Il Codice di Sicurezza non è corretto.",
	PAY_edit:"Edita",
	PAY_save:"Salva",
	DETAIL_quntity_mininum_MOrder:"La quantità non può superare l'ordine minimo (Ordine Min. =",
	DETAIL_quntity_mininum_MSstock:"La quantità non può superare lo stock massimo (Stock Max. =",
	DETAIL_Show_more_photos:"Mostra altre 10 foto",
	DETAIL_add_to_cart:"1 articolo aggiunto al carrello",
	DETAIL_by:"Da",
	DETAIL_report_review:"Segnala Questa Recensione",
	DETAIL_seller_res:"Risposta venditore",
	DETAIL_cannot_shipping_toL:"questo articolo non può essere spedito a ",
    DETAIL_error1:"Seleziona Opzioni",
	CART_remove:"Rimuovi dal carrello?",
	LOGIN_6_30_characters:"6-30 caratteri richiesti",
	Recommended_products:"Prodotti raccomandati",
	Show_more:"Mostra di Più",
	Youmaylike:"Potrebbe interessarti",
	COMMON_Price_onapp:"Acquista con prezzi migliori  sulla App！",
	UserType:"Seleziona almeno una opzione"
};