$IMPORT('/DHMUtils/DHMCommon.js');
$IMPORT('/DHMUtils/DHMInit.js');
$IMPORT('/DHMUtils/DHMSearch.js');
$IMPORT('/DHMUtils/DHMSlide.js');
/*$IMPORT('/registeredSuccessCoupon/registeredSuccessCoupon.js');*/
$IMPORT('/detail/20150608/config.js');
$IMPORT('/detail/20150608/tpl.js');
$IMPORT('/detail/20150608/shipto.js');
$IMPORT('/detail/20150608/detail.js');